use_frameworks!

platform :ios, '8.0'

target 'GRQCocoaPodsDemo_Example' do
  pod 'GRQCocoaPodsDemo', :path => '../'

  target 'GRQCocoaPodsDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
